version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.5.0
    steps:
      - checkout 
      - run:
          name: Install Dependencies
          command: npm install
      # - run:
      #     name: Compile Source Code
      #     command: npm run build
      - run:
          name: Run Unit Tests
          command: npm test
      # - run:
      #     name: Run ESLint
      #     command: npm run lint

workflows:
  version: 2
  build-tests:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main